import Head from 'next/head'
import { Inter } from 'next/font/google'
import Button from '@/components/atoms/Button';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main ${inter.className}`}>
        <h1>Cualquier cosa</h1>
        <Button />
      </main>
    </>
  );
}
