import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function RequestData() {
  const [data, setData] = useState(null);

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts/')
      .then(response => response.json())
      .then(response => {
        // console.log('Data: ', response);
        setData(response);
      });
  }, []);

  const renderItem = item => {
    return (
      <tr>
        <td>{item.userId}</td>
        <td>{item.id}</td>
        <td>{item.title}</td>
      </tr>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main ${inter.className}`}>
        <h1>Ejemplo Request Data</h1>
        <div>
          {!data ? <span>Cargando...</span> : (
            <table>
              <thead>
                <tr>
                  <th>User Id</th>
                  <th>Id</th>
                  <th>Title</th>
                </tr>
              </thead>
              <tbody>{data.map(renderItem)}</tbody>
            </table>
          )}
        </div>
      </main>
    </>
  )
}
