import Head from 'next/head'
import { Inter } from 'next/font/google'
import Button from '@/components/Button'
import Counter from '@/components/Counter'
import WrapperCounter from '@/components/WrapperCounter'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function ShareState() {
  const [count, setCount] = useState(0);

  const increaseCount = () => {
    setCount(count + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main ${inter.className}`}>
        <h1>Ejemplo compartiendo Estados</h1>
        <div>
          <Button increaseCount={increaseCount} />
          <Counter value={count} />
        </div>
        <div>
          <Button increaseCount={increaseCount} />
          <Counter value={count} />
        </div>
        <WrapperCounter />
        <WrapperCounter />
        <WrapperCounter />
        <WrapperCounter />
      </main>
    </>
  )
}
